### ISSUE TITLE
Economically active graduates with NVQ4+ (APS)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#1]
**Summary**
- Date: 2007 - 2018
- Sources: [APS](https://www.nomisweb.co.uk/articles/676.aspx)

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [x] Raw Schema
- [x] Processed
- [ ] Processed Schema

**Challenges and Observations**

**Comment by dede95** [comment]
Where to find the variables for this dataset:
`dataset > query data > Annual Population Survey/Labour Force Survey > annual population survey > variable > select variables` 

I'm guessing in the `Variables` category section, `Qualifications (NVQ) of economically active` is one of the main variables.
