### ISSUE TITLE
STEM postgraduates produced (HESA)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#112]
**Summary**
- Date:
- Source: HESA

**Progress**
- [x] Scoped
- [ ] Calcuated
- [ ] Uploaded
- [ ] Raw schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**

**Comment by Juan-Mateos** [comment]
Refactoring notebooks into scripts and adding flexible methods for nuts labelling
