### ISSUE TITLE
Reverse geocoder

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/beis-indicators#117]
The reverse geocoder takes as an input the `lat,lon` for a observation (eg location of university campus) and determines its geography using the two geographies that we are focusing on in the project (NUTS2 and LEPS)

- [x] Write and test prototype of reverse geocoder in notebook
- [ ] Create package

**Comment by georgerichardson** [comment]
This may already be the method you're using, but if you have a `geopandas` dataframe with lat long `Points` and another with `Polygon`/`Multipolygon` geographies then you can pretty quickly solve this with a join like:

```
points_in_poly = geopandas.sjoin(points, polys, op='within')
```
