### ISSUE TITLE
Auto-NUTS2 version for UK

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#122]
Write a function to automatically detect which NUTS boundary year should be used for each year within an indicator dataset.

This should be able to take a dataframe with columns `nuts_id` and `year` and create a new field for `nuts_year`.

This is to account for the fact that there is a 2 year lag between new NUTS standards being introduced and their enforcement. We don't currently know when different organisations choose to self-enforce the new boundaries within this lag period.

**Comment by georgerichardson** [comment]
Some data sources (e.g. NOMIS/APS) retrospectively apply the more recent NUTS standards. e.g. NOMIS provides data from 2012 to 2016 _all_ using NUTS 2016.

**Comment by mindrones** [comment]
As we discussed in person it doesn't seem to be anymore the case for NOMIS/APS but agree we need to discuss a strategy if this happens in other datasets, in general and in this project.

![image](https://user-images.githubusercontent.com/1309648/73565089-ccae3080-4458-11ea-8049-48d7536fe8bc.png)
