### ISSUE TITLE
Quality of research

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#14]
* Data source: REF
* Explanation: Assessment of the quality of research conducted in different university departments
* Resolution: Institution
* [Link](https://results.ref.ac.uk/(S(pubfnkmzofi0hmugffthjilz))/DownloadResults)

**To Do**:

- [ ] Collect
- [ ] Indicator

**Comment by Juan-Mateos** [comment]
I have already done this.
