### ISSUE TITLE
Fetch datasets for different timeframes

### ISSUE THREAD

**Issue by dede95** [nestauk/beis-indicators#145]
Collect subsets for each dataset according to the year of indicator values' observation and NUTS 2 regions used during the respective year.

**Comment by mindrones** [comment]
Affected PRs:
- #120 
- #127
- #135
- #146

Also see [this comment](https://github.com/nestauk/beis-indicators/issues/122#issuecomment-580857936) for NOMIS

While we do this, we could also address #147 (single source for NUTS)

**Comment by dede95** [comment]
Data collected for different time frames. Another issue opened for refactoring (#213).
