### ISSUE TITLE
Labour market mobility

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#16]
* Data source: ONS
* Explanation: Labour market mobility (outwards plus inwards migration?)
* Resolution: Local Authority
* [Link](https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/migrationwithintheuk/datasets/localareamigrationindicatorsunitedkingdom)

**To Do**:

- [x] Collect
- [x] Aggregate to NUTS2
- [x] Indicator

**Comment by Juan-Mateos** [comment]
I will do this one and also create a NUTS3-NUTS2 lookup and pivoting function

**Comment by Juan-Mateos** [comment]
This is done now. I am however not sure if we can automate the conversion of LADS/NUTS3 to NUTS2 as this depends on the vintage of the classification we are considering, which varies depending on the source. Check the migration notebook for additional information.
