### ISSUE TITLE
% of population employed in professional occupations

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#2]
* Data source: NOMIS/APS
* Explanation: % of population employed as science, research, engineering & technology professionals & associate professionals
* Resolution: NUTS2 (flexible)
* [Link](https://www.nomisweb.co.uk/articles/676.aspx)

- [x] Collect
- [x] Indicator

**Comment by dede95** [comment]
@Juan-Mateos 
Where to find the variables for this dataset:
dataset > query data > Annual Population Survey/Labour Force Survey > annual population survey > variable > select variables
