### ISSUE TITLE
Region code in wrong nuts_year_spec for broadband speed data

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#245]
For the broadband speed data at NUTS2 level I spotted an entry for UKM2 in 2016. [This was removed for NUTS 2016 and replaced with UKM7](https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_the_United_Kingdom#NUTS_2016).

Can all the broadband speed datasets be recreated and checked to make sure that there are no rogue NUTS region IDs out of place?

There are some tools you can import from in `beis_indicators.utils.nuts_utils` which will help to verify whether anything is out of place.

**Comment by dede95** [comment]
Hi, 

UKM2 was found in 2016 because NUTS 2013 was used during that year. https://ec.europa.eu/eurostat/web/nuts/history

@Juan-Mateos
