### ISSUE TITLE
Switch "Relative" to "Ranking" and include in plot titles

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#251]
- Consider replacing "Relative" (on the Absolute/Relative buttons) with "Ranking"
- Consider replacing the two buttons with a single "Ranking" on/off toggle
- Regardless of which word is used, it would be worth including it in the plot title(?) if it’s an easy thing to do e.g. `Expenditure (to nearest 1000) [EUR]` becomes `Relative Expenditure (to nearest 1000) [EUR]` or `Ranking by Expenditure (to nearest 1000) [EUR]`

For reference, talking about this area of the plots:
![image](https://user-images.githubusercontent.com/6348211/84253135-78524600-ab07-11ea-9ce7-6db7da041f10.png)

**Comment by mindrones** [comment]
From feedback: eventually have a label – always visible – beside the 2 buttons.
