### ISSUE TITLE
REF scores in STEM disciplines (HEFCE)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#52]
**Summary**
- Name: REF scores in STEM disciplines
- Date: 2014
- [Link](https://results.ref.ac.uk/(S(uf2bo5kabqfs52hu3anazro3))/DownloadResults)

**Challenges and Observations**

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [ ] Raw schema
- [ ] Processed
- [ ] Processed Schema

**Comment by mindrones** [comment]
Closed by #208, closing
