### ISSUE TITLE
University research income (HESA)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#53]
**Summary**
- Name: University research income
- Date: 2014 - 2017
- [Link](https://www.hesa.ac.uk/data-and-analysis/estates)

**Challenges and Observations**

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [x] Raw schema
- [ ] Processed
- [ ] Processed Schema

**Comment by Juan-Mateos** [comment]
Refactoring notebooks into scripts and adding flexible methods for nuts labelling
