### ISSUE TITLE
Income in STEM disciplines (UKRI)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#54]
**Summary**
- Name: University research income
- Date: 2006 - 2019
- [Source Link](https://gtr.ukri.org/)

**Challenges and Observations**
- This is income for projects lead by local institutions

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [ ] Raw schema
- [x] Processed
- [ ] Processed Schema

**Comment by Juan-Mateos** [comment]
Following from the meeting with BEIS I have changed this from level of funding to number of projects led by organisations in the area.

**Comment by Juan-Mateos** [comment]
Refactoring notebooks into scripts and adding flexible methods for nuts labelling
