### ISSUE TITLE
University buildings (HESA)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#55]
**Summary**
- Name: University research income
- Date: 2014 - 2017
- [Source Link](https://www.hesa.ac.uk/data-and-analysis/estates)

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [x] Raw schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**

**Comment by Juan-Mateos** [comment]
Refactoring notebooks into scripts and adding flexible methods for nuts labelling
