### ISSUE TITLE
Private sector R&D workforce (Eurostat)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#64]
**Summary**
- Date: 2012 - 2016
- Sources: Crunchbase

**Progress**
- [x] Scoped
- [x] [Collected](https://github.com/nestauk/beis-indicators/blob/master/data/processed/eurostat/eurostat_private_rd_workforce_data.csv)
- [x] Uploaded
- [x] Raw Schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**
- NUTS 2 codes are only updated to the NUTS 2 2013 codes (i.e. these changes do not occur: UKM2-> UKM7 & UKM3 ->UKM9)

**Comment by mindrones** [comment]
This has been done in https://github.com/nestauk/beis-indicators/pull/49, closing `stage:raw` (see https://github.com/nestauk/imt_playbook/issues/54).
