### ISSUE TITLE
Economic complexity (BRES)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#65]
**Summary**
- Date: 2012 - 2016
- Sources: BRES

**Progress**
- [x] Scoped
- [x] Collected
- [ ] Calculated
- [ ] Uploaded
- [ ] Raw Schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**
- Does not include NI

**Comment by mindrones** [comment]
Closed by #183, closing
