### ISSUE TITLE
Business Enterprise R&D (BERD) (Eurostat)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#67]
**Summary**
- Date: 
- Sources: Eurostat

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [x] Raw Schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**
- Only goes up to 2016 for UK NUTS2 regions; NUTS 2 codes are only updated to the NUTS 2 2013 codes (i.e. these changes do not occur: UKM2-> UKM7 & UKM3 ->UKM9)

**Comment by mindrones** [comment]
This has been done in https://github.com/nestauk/beis-indicators/pull/49, closing `stage:raw` (see https://github.com/nestauk/imt_playbook/issues/54).
