### ISSUE TITLE
Average external investment per formal spin-out (HE-BCI)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#79]
**Summary**
- Date: 2014 - 2017
- Sources: HE-BCI

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [ ] Raw Schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**

**Comment by Juan-Mateos** [comment]
Reopened to update NUTS2 classification and refactor notebooks into scripts
