### ISSUE TITLE
Students in STEM disciplines (HESA)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#91]
**Summary**
- Date: 2014 - 2017
- Sources: HESA

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [x] Raw Schema
- [ ] Processed
- [ ] Processed Schema

**Challenges and Observations**

**Comment by Juan-Mateos** [comment]
Refactoring notebooks into scripts and adding flexible methods for nuts labelling
