### ISSUE TITLE
% of the population with tertiary education (APS)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#92]
**Summary**
- Date: 2007 - 2018
- Sources: APS

**Progress**
- [x] Scoped
- [x] Collected
- [x] Uploaded
- [x] Raw Schema
- [x] Processed
- [ ] Processed Schema

**Challenges and Observations**

**Comment by dede95** [comment]
@georgerichardson @mindrones Since this indicator indicator has been deleted in the spreadsheet (since it's the exact same as issue #1, which we kept), is it okay to delete this issue?

**Comment by dede95** [comment]
Duplicate of #1
